base:
  # ModelArguments
  model_name_or_path: facebook/opt-1.3b
  model_4bit: false
  # TrainingArguments
  wandb_project: debug
  wandb_name: testing123
  save_dir: /home/lune/nas2/lightning/lightning-template/checkpoint
  devices: [0,1,2,3,4,5,6,7]
  do_train: true
  do_test: false
  scheduler_type: ReduceLROnPlateau
  # data
  lr: 0.0002
  max_epochs: 10
  max_samples: 100
  source_max_len: 1000
  target_max_len: 1000
  predict_with_generate: false
  per_device_train_batch_size: 2
  per_device_eval_batch_size: 2